---
title: "Star Wars 4- Text file conversion"
author: "Samuel Rea"
date: "`r Sys.Date()`"
output: html_document
---
loading in the packages and setting working directory. Commented out currently
```{r}
#you may have to install some of the packages using the install.packages() function then library them
#setwd("/Users/samrea5/Desktop/uvafourthyear/second_semester/DS 4000 data science project/project1")
```

Load in the data that you need to do the text analysis just starting with 4
```{r}
#reading the lines into an object in R
sw <- iconv(readLines("StarWars_EpisodeIV_script.txt", encoding = "UTF-8"), to = "ASCII", sub = " ")

#inspecting the first lines to make sure everything parced together correctly
sw[1:70]

#we are setting auxillary strings so we are able to jump to the correct location in the lines for the character name and the dialoug that he uses
b10 = "          "
b20 = "                    "
# this gives us a variable that is the length of the number of lines so we can properly loop through the data to place it into a data frame
nlines = length(sw)
```

now that we have a text file in R we can convert the text file to a text file that we can work with aka properly encoded
```{r}
#dialogue starts on line 50 so set i to 50 or ine 50
i = 50
#what im saving the file as
output_file <- file("EpisodeIV_dialogues.txt", "w")


#if you want to go through this loop you can simple stuff that just recognizes when its a character line saves and changes the format and then same thing for a dialogue line. This also loops through and removes things like description of set or what characters are doing. 
# Main loop
while (i <= length(sw)) {
  # If empty line
  if (sw[i] == "") {
    i <- i + 1  # Move to the next line
  } else {
    # If script description or short line, move to the next line
    if (substr(sw[i], 1, 1) != " " || nchar(sw[i]) < 10) {
      i <- i + 1
    } else {
      # If character name
      if (substr(sw[i], 1, 20) == b20) {
        if (substr(sw[i], 21, 21) != " ") {
          tmp_name <- substr(sw[i], 21, nchar(sw[i], "bytes"))
          cat(tmp_name, "\n", file = output_file)
        }
        i <- i + 1
      }
      # If dialogue
      if (substr(sw[i], 1, 10) == b10) {
        if (substr(sw[i], 11, 11) != " ") {
          tmp_diag <- substr(sw[i], 11, nchar(sw[i], "bytes"))
          cat(tmp_diag, "\n", file = output_file)
        }
        i <- i + 1
      }
    }
  }
}

# Close the file connection
close(output_file)
```

All of the preprocessing for Movie 4 is now done.
